const doctors = [
    {
      firstName: 'John',
      lastName: 'Smith',
      gender: 'Male',
      specialization: 'General Practitioner',
      latitude: 48.837225,
      longitude: 2.296916,
    },
    {
      firstName: 'Jane',
      lastName: 'Doe',
      gender: 'Female',
      specialization: 'Pediatrician',
      latitude: 48.865261,
      longitude: 2.288665,
    },
    {
      firstName: 'Michael',
      lastName: 'Johnson',
      gender: 'Male',
      specialization: 'Dermatologist',
      latitude: 48.879534,
      longitude: 2.293597,
    },
    {
      firstName: 'Emily',
      lastName: 'Williams',
      gender: 'Female',
      specialization: 'Cardiologist',
      latitude: 48.838530,
      longitude: 2.357142,
    },
    {
      firstName: 'David',
      lastName: 'Anderson',
      gender: 'Male',
      specialization: 'Orthopedic Surgeon',
      latitude: 48.842477,
      longitude: 2.397540,
    },
    {
      firstName: 'Sarah',
      lastName: 'Brown',
      gender: 'Female',
      specialization: 'Ophthalmologist',
      latitude: 48.856496,
      longitude: 2.394226,
    },
    {
      firstName: 'Christopher',
      lastName: 'Lee',
      gender: 'Male',
      specialization: 'ENT Specialist',
      latitude: 48.861583,
      longitude: 2.366611,
    },
    {
      firstName: 'Olivia',
      lastName: 'Martinez',
      gender: 'Female',
      specialization: 'Neurologist',
      latitude: 48.854663,
      longitude: 2.330132,
    },
    {
      firstName: 'William',
      lastName: 'Garcia',
      gender: 'Male',
      specialization: 'Dentist',
      latitude: 48.884134,
      longitude: 2.383862,
    },
    {
      firstName: 'Ava',
      lastName: 'Lopez',
      gender: 'Female',
      specialization: 'Psychiatrist',
      latitude: 48.893503,
      longitude: 2.323266,
    },
    {
      firstName: 'James',
      lastName: 'Harris',
      gender: 'Male',
      specialization: 'Urologist',
      latitude: 48.897678,
      longitude: 2.346955,
    },
    {
      firstName: 'Mia',
      lastName: 'Perez',
      gender: 'Female',
      specialization: 'Gastroenterologist',
      latitude: 48.873184,
      longitude: 2.317945,
    },
    {
      firstName: 'Alexander',
      lastName: 'Allen',
      gender: 'Male',
      specialization: 'Rheumatologist',
      latitude: 48.883344,
      longitude: 2.332536,
    },
    {
      firstName: 'Sophia',
      lastName: 'Turner',
      gender: 'Female',
      specialization: 'Oncologist',
      latitude: 48.872958,
      longitude: 2.362920,
    },
    {
      firstName: 'Ethan',
      lastName: 'King',
      gender: 'Male',
      specialization: 'Endocrinologist',
      latitude: 48.874127,
      longitude: 2.343489,
    },
  ];
  
  export default doctors;
  